### ISSUE TITLE
npm install --save foundation-v2-vertcoin - [nodemon] app crashed - waiting for file changes before starting...

### ISSUE THREAD

**Issue by blackmennewstyle** [blinkhash/foundation-v2-server#7]
I followed the tutorial: https://blinkhash.com/docs/foundation, however i performed `npm install --save foundation-v2-vertcoin` instead of `npm install --save foundation-v2-bitcoin`.

There is actually two issues, the generated file `configs/pools/example.js` is actually the one for `bitcoin` instead of `vertcoin` :/

The second issue is that error when starting the pool
```
npm run start

> foundation-v2-server@0.0.1 start /home/ceedii/foundation-server
> nodemon ./index.js

[nodemon] 2.0.19
[nodemon] to restart at any time, enter `rs`
[nodemon] watching path(s): *.*
[nodemon] watching extensions: js,mjs,json
[nodemon] starting `node ./index.js`
/home/ceedii/foundation-server/server/main/loader.js:51
    if (config.name.split(' ').length > 1) {
                    ^

TypeError: Cannot read property 'split' of undefined
    at Loader.checkPoolNames (/home/ceedii/foundation-server/server/main/loader.js:51:21)
    at /home/ceedii/foundation-server/server/main/loader.js:122:20
    at Array.forEach (<anonymous>)
    at Loader.handleConfigs (/home/ceedii/foundation-server/server/main/loader.js:117:36)
    at Threads.setupThreads (/home/ceedii/foundation-server/server/main/threads.js:25:30)
    at /home/ceedii/foundation-server/index.js:17:57
    at Client._connectionCallback (/home/ceedii/foundation-server/database/main/client.js:42:7)
    at Client._handleReadyForQuery (/home/ceedii/foundation-server/node_modules/pg/lib/client.js:279:14)
    at Connection.emit (events.js:311:20)
    at /home/ceedii/foundation-server/node_modules/pg/lib/connection.js:114:12
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by blinkhash** [comment]
Addressed in Discord, but I'll mention it here as well:

- The reason why the example.js file is for Bitcoin is because v2-server is intended to support multiple pools if necessary, and BTC is most often the default. You can copy + modify that file directly to suit your needs though. Look through https://blinkhash.com/docs/foundation/v2/configurations for documentation on config data.
- The issue on startup is because it looks like you took the config file from v2-vertcoin. That one specifically is missing a few important properties that v2-server configurations have, so it won’t work properly. Check the repository here for a v2-server configuration that works with Vertcoin: https://github.com/blinkhash/foundation-v2-configurations.
